FROM node:12-alpine as build

WORKDIR /usr/app

COPY package.json .
COPY yarn.lock .

RUN yarn 

COPY  . .

RUN REACT_APP_BASE_URL=example.com yarn build

FROM nginx:1.15

COPY --from=build /usr/app/build /usr/share/nginx/html
